#!/bin/bash

usage() {
    echo "Usage: $0 <PluginName>"
}

src=`dirname $0`
name=$1
package=$2
lower=`echo ${name} | tr '[:upper:]' '[:lower:]'`
if [ -z "$name" ]; then
    usage >&2
    exit 1
fi
echo Template Folder: $src
echo Plugin name: $name
if [ -e "$name" ]; then
    echo "File $name already exists." >&2
    exit 1
fi

set -e
mkdir -v "$name"
for file in "$src"/* "$src"/.??*; do
    case "`basename $file`" in
	template|.git|"$name")
	    continue
	    ;;
	*)
	    cp -Rv "$file" "$name"
	    ;;
    esac
done

mv -v "$name"/src/main/java/com/cavetale/template/{Template,${name}}Plugin.java
mv -v "$name"/src/main/java/com/cavetale/template/{Template,${name}}Command.java
mv -v "$name"/src/main/java/com/cavetale/{template,${lower}}
mv -v "$name"/src/test/java/com/cavetale/template/{Template,${name}}Test.java
mv -v "$name"/src/test/java/com/cavetale/{template,${lower}}
find "$name" -type f -exec sed -i "s/template/${lower}/g;s/Template/${name}/g" {} \;

if [ ! -z "$package" ]; then
    path=`echo $package | sed 's|\.|/|g'`
    echo package $package $path
    mkdir -p "$name"/src/main/java/"$path"
    mv -v "$name"/src/main/java/com/cavetale/"$lower" "$name"/src/main/java/"$path"/
    rmdir --ignore-fail-on-non-empty -p "$name"/src/main/java/com/cavetale/

    mkdir -p "$name"/src/test/java/"$path"
    mv -v "$name"/src/test/java/com/cavetale/"$lower" "$name"/src/test/java/"$path"/
    rmdir --ignore-fail-on-non-empty -p "$name"/src/test/java/com/cavetale/

    find "$name" -type f -exec sed -i "s/com\.cavetale/${package}/g" {} \;
fi

echo Finished setting up $name
exit 0
