main: com.cavetale.template.TemplatePlugin
name: Template
version: 0.1
api-version: 1.13
description: Template Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  template:
    aliases: []
    description: Template Command
    permission: template.template
    permission-message: You do not have permission!
    usage: /<command>
permissions:
  template.template:
    description: Use /template
    default: op
    children:
      template.child: true
