main: com.cavetale.template.TemplatePlugin
name: Template
version: 0.1
api-version: 1.13
description: Template Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  template:
    aliases: []
    description: Template Command
    permission: template.template
    usage: |-
      /template
permissions:
  template.template:
    description: Use /template
    default: op
