main: com.cavetale.template.TemplatePlugin

name: Template
version: 0.1
description: Template Plugin
api-version: 1.18

author: StarTux
website: https://github.com/StarTux/Template

depend: [Core]
softdepend: []

commands:

  template:
    aliases: []
    description: Template Command
    permission: template.template
    usage: |-
      /template

permissions:

  template.template:
    description: Use /template
    default: op
