main: com.cavetale.template.TemplatePlugin
name: Template

version: ${version}
api-version: '1.21'

author: StarTux
website: https://github.com/StarTux/Template
description: Template Plugin

depend: [Core]
softdepend: []

commands:

  template:
    aliases: []
    description: Template Command
    permission: template.template
    usage: |-
      /template

permissions:

  template.template:
    description: Use /template
    default: op
